### ISSUE TITLE
Onboard new users with Fortmatic

### ISSUE THREAD

**Issue by vinosamari** [bl0cknumber/nuxt-web3#12]
Can I use fortmatic as a provider to help onboard new users that aren't familiar with using a crypto wallet?

The docs read that the provider should be a property in the nuxt.config.js file and Fortmatic's Javascript SDK won't work with that.

Any workarounds or help will be highly appreciated.

**Comment by bl0cknumber** [comment]
Yes you can, you can set directly the provider without nuxt.config.js file

```js
import { Fortmatic } from "fortmatic";
const fm = new Formatic('your_api_key');
window.web3 = new this.$Web3(fm.getProvider())
```

**Comment by vinosamari** [comment]
AWESOME!! Thanks for being so helpful. I can't wait to contribute to the project. Cheers
